service: rg-serverless
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors:
            origin: '*'
            allowCredentials: false
          integration: lambda-proxy